project:
  output-dir: out
  type: website
  resources:
    - /data/irena-totals.csv
    - /data/ipcc-decarbonisation-costs-processed.csv
    - solution-beeswarm/assets/*.svg
  render:
    - analysis/*/index.qmd
    - solution-beeswarm/index.qmd
    - map/index.qmd  

execute:
  freeze: auto
  