project:
  output-dir: out
  type: website
  resources:
    - /data/irena-totals.csv

website:
  twitter-card:
    creator: "@360info_global"
    image: https://360info-electricitytransition.pages.dev/map/electricity-transition-featuremedia
  open-graph:
    image: https://360info-electricitytransition.pages.dev/map/electricity-transition-featuremedia
    site-name: 360info

execute:
  freeze: auto
  