project:
  output-dir: out
  type: website
  resources:
    - /data/irena-totals.csv
    - /data/ipcc-decarbonisation-costs-processed.csv
    - solution-beeswarm/assets/*.svg
  render:
    - analysis/*/index.qmd
    - solution-beeswarm/index.qmd
    - map/index.qmd

website:
  twitter-card:
    creator: "@360info_global"
    image: https://360info-electricitytransition.pages.dev/map/electricity-transition-featuremedia.png
  open-graph:
    image: https://360info-electricitytransition.pages.dev/map/electricity-transition-featuremedia.png
    site-name: 360info

execute:
  freeze: auto
  